FROM node:lts-alpine
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# RUN apk --no-cache add --virtual builds-deps build-base python3

COPY package.json .
RUN yarn install
RUN yarn add pm2 -g

COPY . .

RUN yarn build

CMD ["yarn", "pm2"]
