FROM node:lts-alpine
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# RUN apk --no-cache add --virtual builds-deps build-base python3

COPY package.json .
RUN yarn install

COPY . .

RUN yarn build

CMD ["yarn", "start"]
