- hosts: webservers
  become: true
  become_method: sudo
  vars:
    container_count: 3
    default_container_name: rsr-web
    default_container_image: node:16
    nodejs_version: 16
    ansible_distribution_release: "xenial"

  tasks:
    - name: Install gnupg
      apt:
        update_cache: yes
        name: gnupg
        state: present
      
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install the nodejs
      apt:
        update-cache: yes
        name: nodejs
        state: present

    - name: Install "pm2" node.js package globally
      community.general.npm:
        name: pm2
        global: yes

    - name: Create pm2 ecosystem file for Next
      template:
        src: templates/ecosystem.config.js
        dest: /home/ophzl/ecosystem.config.js

    - name: Install yarn globally
      community.general.npm:
        name: yarn
        global: yes

    # - name: Install yarn globally
    #   community.general.npm:
    #     name: yarn
    #     global: yes

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - rsync
        state: latest
        update_cache: true
    
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Update apt and install docker-compose
      apt:
        name: docker-compose-plugin
        state: latest
        update_cache: true
