name: 'Application'
on: [push]
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build application
        run: yarn build

  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build the stack and launch e2e tests
        run: docker-compose up -d & yarn test:e2e
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-artifacts
          path: test-results/