name: 'Application'
on: [push]
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build application
        run: yarn 
  
  create-env-file:
    runs-on: ubuntu-latest
    steps:
      - name: Make env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASS: ${{ secrets.DB_PASS }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          file_name: .env
          fail_on_empty: true

  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [build, create-env-file]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build the stack
        run: ENV_FILE="/github/workspace/.env" docker-compose -f docker-compose.dev.yml up -d
      - name: Launch e2e tests
        if: success()
        run: yarn test:e2e
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-artifacts
          path: test-results/