name: 'Test'
on: [push]
jobs:
  unit-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Launch unit tests
        run: yarn test

  # e2e-tests:
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build stack
  #       run: docker compose -f docker-compose.dev.yml up -d --build
  #     - name: Install dependencies
  #       run: npm install --force
  #     - name: Install playwright browsers
  #       run: npx playwright install
  #     - name: Install playwright deps
  #       run: npx playwright install-deps
  #     - name: Launch e2e tests
  #       run: npm run test:e2e
  #     - uses: actions/upload-artifact@v2
  #       if: always()
  #       with:
  #         name: test-artifacts
  #         path: test-results/
  #     - name: Stop containers
  #       if: always()
  #       run: docker compose -f docker-compose.dev.yml down