name: 'Test'
on:
  - pull_request

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Launch unit tests
        run: yarn test

  deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: easingthemes/ssh-deploy@v2.2.11
        with:
        # Private Key
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        # Remote host
          REMOTE_HOST: 52.47.179.38
        # Remote user
          REMOTE_USER: admin
        # Remote port
          # REMOTE_PORT: # optional, default is 22
        # Source directory
          # SOURCE: # optional, default is
        # Target directory
          TARGET: /home/admin/next # optional, default is /home/REMOTE_USER/
        # Arguments to pass to rsync
          # ARGS: # optional, default is -rltgoDzvO
        # An array of folder to excludehh
          EXCLUDE: node_modules
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan 52.47.179.38 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - run: ssh admin@52.47.179.38 "ls"
      - name: Deploy with rsync
        run: rsync -avz ./ admin@52.47.179.38:next
      - run: ssh admin@52.47.179.38 "cd next && sudo docker compose -f docker-compose.dev.yml up"
      - run: ssh admin@52.47.179.38 "pm2 startOrReload ecosystem.config.js"

  # e2e-tests:
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build stack
  #       run: docker compose -f docker-compose.dev.yml up -d --build
  #     - name: Install dependencies
  #       run: npm install --force
  #     - name: Install playwright browsers
  #       run: npx playwright install
  #     - name: Install playwright deps
  #       run: npx playwright install-deps
  #     - name: Launch e2e tests
  #       run: npm run test:e2e
  #     - uses: actions/upload-artifact@v2
  #       if: always()
  #       with:
  #         name: test-artifacts
  #         path: test-results/
  #     - name: Stop containers
  #       if: always()
  #       run: docker compose -f docker-compose.dev.yml down